CHANGELOG.md, algosdk/algod.py, algosdk/constants.py, algosdk/encoding.py, algosdk/transaction.py, algosdk/util.py, algosdk/wallet.py, setup.py, test_integration.py
- remove dependence on expiration time for managing the handle in wallet.py
- fix optional parameter support in transactions_by_address
=> documentation fixes

algosdk/algod.py, example_custom_header.py
Adds support for multiple different headers on the algod client class and in all of the internal methods - backwards compatible for existing code
=> Additional header capability to algod init and all the methods

CHANGELOG.md, algosdk/algod.py, algosdk/util.py, setup.py
=> update version to 1.0.5

algosdk/constants.py, algosdk/encoding.py, algosdk/transaction.py, test_unit.py
- put transaction type strings ("pay", "keyreg", etc) into constants.py
=> support for asset config transactions

setup.py
in response to a comment on #29 Error in generate_account()
=> add requirement for cryptography package version

README.md, test_unit.py
for #28 Add code samples to README
=> add asset examples

algosdk/constants.py, algosdk/error.py, algosdk/transaction.py, test_unit.py
- add group field to asset transaction encode/decode
=> add leases to transactions

algosdk/encoding.py, algosdk/transaction.py, test_unit.py
- move header fields handling to Transaction superclass to minimize work in subclasses
=> refactor transaction dictify/undictify

algosdk/constants.py, algosdk/error.py, algosdk/transaction.py
=> add check for maximum number of transactions in transaction groups and number of accounts in multisigs

README.md, algosdk/error.py, algosdk/logic.py, algosdk/template.py, algosdk/transaction.py, setup.py, test_unit.py
- add test for raising this error
- update version to 1.1.0
- fix byte injection bug
Build will fail until some tests in algorand-sdk-testing are updated.
=> add flag for checking empty addresses in AssetConfigTxn

algosdk/constants.py, algosdk/error.py, algosdk/transaction.py, test_unit.py
#55 Add decimals field to assets
tests will fail until https://github.com/algorand/algorand-sdk-testing/pull/31 is merged
=> add decimals to AssetConfigTxn

CHANGELOG.md, setup.py
=> Release - v1.1.1

algosdk/transaction.py
=> add get_txid() to SignedTransaction, MultisigTransaction, LogicSigTransaction

algosdk/algod.py
add support for fetching raw msgpack bytes blocks from algod
=> Local raw block

.travis.yml, Dockerfile, Makefile, README.md
Run the tests with a tags whitelist. When adding new functionality we will need to update the whitelist.
=> Update cucumber tests to use a whitelist.

Makefile, algosdk/testing/dryrun.py, test/steps/v2_steps.py, test_unit.py
* DryrunTestCaseMixin class to be used as a mixin for unittest.TestCase
* Special asserts
assertPass, assertReject
assertError, assertNoError
assertGlobalStateContains, assertLocalStateContains
* Integration tests
=> TEAL test harness with dryrun

Makefile, run_integration.sh, test/environment.py, test/steps/v2_steps.py
Closes #129. Tests pass, but there is some problem in the dryrun tests causing the overall Travis build to fail. But this PR does not cover dryrun.
=> Add implementation for @unit.responses tests.

algosdk/future/transaction.py, run_integration.sh, test/steps/v2_steps.py
New foreign asset field + unit test updates
=> Add support for foreign assets.

algosdk/future/transaction.py, algosdk/kmd.py, algosdk/v2client/algod.py
Fix docs
Fix kmd.sign_transaction
=> Update v2 compile and dryrun doc strings

algosdk/transaction.py
=> remove need for nonexistent constant

algosdk/kmd.py
#111 fixes error where creating a new wallet expects something different from the node
=> check for empty result in list_wallets

algosdk/algod.py, algosdk/error.py, algosdk/v2client/algod.py, algosdk/v2client/indexer.py
- add round_num variable to functions using block or round, since block is inconsistent with other variable names and round is a reserved function in python
#127
=> add optional round_num argument to v2 clients for 'round' vs 'block' naming consistency

algosdk/future/transaction.py, algosdk/transaction.py, test_integration.py, test_unit.py
=> fix logic multisig transactions not being accepted

Dockerfile
Changed the dockerfile to install the local version of the SDK. This will make testing local changes a lot easier.
Also updated the python base image.
=> Install local package in dockerfile

algosdk/constants.py
allows `algod.algod_request("GET", "/genesis")`
=> add /genesis to unversioned paths

README.md
=> Updated Node setup section with good link to setup a node

.travis.yml
Add secure variables for docker and add a docker login to the .travis.yaml file.
=> Add docker login to travis config

Makefile, algosdk/future/transaction.py, algosdk/transaction.py, test/steps/steps.py, test_unit.py
This PR is to support creating transactions with a fee under mintxnfee since other txns in the group will be paying.
=> Fee pooling SDK change

algosdk/error.py, algosdk/v2client/algod.py
Fixes #193. @jasonpaulos let me know if this works. I ran `make docker-test` and all tests passed (I didn't expect any to fail in any case).
I took the simple approach of just raising the `JSONDecodeError` that's caught.
=> Raise JSONDecodeError instead of None (#193)

algosdk/mnemonic.py, examples/account_backup_example.py, test_unit.py
Fixes https://github.com/algorand/py-algorand-sdk/issues/187.
=> Deprecate to_public_key and remove internal usage of to_public_key

algosdk/encoding.py, algosdk/error.py, algosdk/future/transaction.py, examples/log_sig_example.py, test_unit.py
Implement the improvements from https://github.com/algorand/go-algorand-sdk/pull/230
=> Signing support for rekeying to LogicSig/MultiSig account

Makefile, test/steps/v2_steps.py
Implement tests from algorand/algorand-sdk-testing#145
=> Implement cucumber keyreg encoding tests

algosdk/v2client/algod.py, algosdk/v2client/indexer.py
Adding a default User-Agent header to the v2 algod client to address #237
=> Default header

CHANGELOG.md, algosdk/future/transaction.py, setup.py
- Create dryrun (#259)
- Support Foreign objects as ABI arguments and address ARC-4 changes (#251)
- Add requirement to fetch behave source code and update readme (#262)
- Fix wait for confirmation function (#263)
- Add a default User-Agent header to the v2 algod client (#260)
- ABI Interaction Support for Python SDK (#247)
- ABI Type encoding support (#238)
- Add type hints and clean up ABI code (#253)
- Add CircleCI configs to the Python SDK repo (#246)
- Re-format local and global state to work with correct msgpack encoding (#274)
=> FOR REVIEW ONLY - py-algorand-sdk v1.9.0

run_integration.sh
For the actual new functionality intended please refer to #268
=> revert to point testing harness to sdk testing's master branch

CHANGELOG.md, setup.py
- New keyreg txn field (#244)
- C2C Feature and Testing (#268)
- Add App creator to account balances (#277)
- Add ABI and ATC to Sphinx (#289)
- Change __init__.py to include v2client import (#243)
- Updates to pipeline (#279)
- Add CircleCI build step to generate docsets (#285)
- revert to point testing harness to sdk testing's master branch (#288)
- Partially fix types for atomic transaction composer (#290)
- Update `langspec.json` for Teal6 (#292)
=> FOR REVIEW ONLY - py-algorand-sdk v1.10.0

CHANGELOG.md, Makefile, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, setup.py, test/steps/v2_steps.py
- Support unlimited assets REST API changes. (#295)
- Fix the cucumber test wording around block rounds in indexer asset balance lookup (#301)
=> FOR REVIEW ONLY - py-algorand-sdk v1.11.0b1

CHANGELOG.md, setup.py
- Support unlimited assets REST API changes. (#295)
- Fix the cucumber test wording around block rounds in indexer asset balance lookup (#301)
=> FOR REVIEW ONLY - py-algorand-sdk v1.11.0

algosdk/dryrun_results.py
=> fixed typo in lsig trace

algosdk/future/transaction.py
We should include the app address of foreign apps
=> adding foreign-app-addr to dryrun creator

.readthedocs.yaml, CHANGELOG.md, setup.py
- Fix readthedocs by providing root requirements.txt (#332)
=> FOR REVIEW ONLY - py-algorand-sdk v1.13.1

algosdk/v2client/algod.py, run_integration.sh, tests/steps/application_v2_steps.py
This PR adds the GetApplicationBoxes API endpoint in the v2 `algod` client and adds cucumber integration tests.
=> Box Storage: Add GetApplicationBoxes API and cucumber steps

tests/unit_tests/test_other.py
This PR adds additional version consolidation changes to the [existing TEAL/AVM language consolidation PR](https://github.com/algorand/py-algorand-sdk/pull/361).
=> Consolidate AVM and TEAL versions in `test_other.py`

CHANGELOG.md, README.md, algosdk/algod.py, algosdk/encoding.py, algosdk/future/transaction.py, algosdk/kmd.py, algosdk/template.py, algosdk/transaction.py, setup.py, tests/unit.tags
* Deprecation: Add deprecation warnings on v1 algod API and old transaction format by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/381
* enhancement: add unit test for ParticipationUpdates field by @shiqizng in https://github.com/algorand/py-algorand-sdk/pull/386
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.17.0...v1.18.0
=> FOR REVIEW ONLY - py-algorand-sdk v1.18.0

.test-env, Makefile, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, test-harness.sh, tests/steps/other_v2_steps.py, tests/unit.tags
Add tests to new REST API code.
=> REST API: Add algod block hash endpoint, add indexer block header-only param.

.test-env, Makefile, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, setup.py, test-harness.sh, tests/steps/other_v2_steps.py, tests/unit.tags
* REST API: Add algod block hash endpoint, add indexer block header-only param. by @winder in https://github.com/algorand/py-algorand-sdk/pull/390
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.18.0...v1.19.0
=> FOR REVIEW ONLY - py-algorand-sdk  v1.19.0

CHANGELOG.md, algosdk/atomic_transaction_composer.py, algosdk/box_reference.py, algosdk/encoding.py, algosdk/error.py, algosdk/future/transaction.py, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, setup.py, tests/integration.tags, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/steps/steps.py, tests/unit.tags, tests/unit_tests/test_other.py, tests/unit_tests/test_transaction.py
* Boxes: Add support for Boxes by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/348
* `class StateSchema`'s method `undictify()` now returns a `StateSchema` object instead of a python `dict`
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.19.0...v1.20.0
=> FOR REVIEW ONLY: py-algorand-sdk v1.20.0

.test-env, algosdk/abi/array_static_type.py, algosdk/abi/base_type.py, tests/unit_tests/test_abi.py
Fixes https://github.com/algorand/js-algorand-sdk/issues/497
=> Enhancement: allowing zero length static array

algosdk/abi/string_type.py, tests/unit_tests/test_abi.py
Fixes: https://github.com/algorand/js-algorand-sdk/issues/699
=> Bug-Fix: encode ABI string with non-ASCII characters

CHANGELOG.md, README.md, algosdk/abi/array_static_type.py, algosdk/abi/base_type.py, algosdk/abi/string_type.py, examples/custom_header_example.py, examples/log_sig_example.py, examples/multisig_example.py, examples/notefield_example.py, examples/rekey_example.py, examples/tokens.py, examples/transaction_group_example.py, setup.py, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/steps/steps.py, tests/unit_tests/test_abi.py
* Bug-Fix: encode ABI string with non-ASCII characters by @ahangsu in https://github.com/algorand/py-algorand-sdk/pull/402
* Tests: Migrate v1 algod dependencies to v2 in cucumber tests by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/400
* Enhancement: allowing zero length static array by @ahangsu in https://github.com/algorand/py-algorand-sdk/pull/401
* README: Delete Travis CI Badge  by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/404
* examples: Migrate v1 algod usage to v2 algod by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/403
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.20.1...v1.20.2
=> FOR REVIEW ONLY: py-algorand-sdk v1.20.2

algosdk/atomic_transaction_composer.py
Update implementation against develop branch.
**DO NOT SQUASH MERGE**
=> Merge develop into `feature/v2.0.0-break`

algosdk/v2client/algod.py
=> Fix: Minor fix for `exclude` argument in `account_info`

CHANGELOG.md, _examples/account.py, _examples/application/approval.teal, _examples/application/approval_refactored.teal, _examples/application/clear.teal, _examples/apps.py, _examples/asa.py, _examples/atc.py, _examples/atomic_transfers.py, _examples/calculator/approval.teal, _examples/calculator/clear.teal, _examples/calculator/contract.json, _examples/codec.py, _examples/debug.py, _examples/indexer.py, _examples/kmd.py, _examples/lsig.py, _examples/lsig/sample_arg.teal, _examples/lsig/simple.teal, _examples/overview.py, _examples/participation.py, _examples/utils.py, algosdk/v2client/algod.py, setup.py
* Fix: Minor fix for `exclude` argument in `account_info` by @ahangsu in https://github.com/algorand/py-algorand-sdk/pull/449
* Documentation: Adding examples to be pulled in to docs by @barnjamin in https://github.com/algorand/py-algorand-sdk/pull/441
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v2.1.0...v2.1.1
=> FOR REVIEW ONLY: py-algorand-sdk v2.1.1

.test-env, algosdk/atomic_transaction_composer.py, algosdk/v2client/models/simulate_request.py, tests/integration.tags, tests/steps/other_v2_steps.py
Update model file from https://github.com/algorand/go-algorand/pull/5354/ feature introduction.
=> Algod: Simulation run with extra budget per transaction group

algosdk/v2client/algod.py, tests/steps/other_v2_steps.py
Add msgpack query param to deltas endpoints.
=> algod: Add msgpack query param to deltas endpoints

.test-env, examples/indexer.py, examples/utils.py, tests/steps/application_v2_steps.py
Implements test changes from https://github.com/algorand/algorand-sdk-testing/pull/309
=> Fix: Fix indexer sync issue in cucumber tests

.circleci/config.yml
Add Python 3.12 to the test matrix
=> Testing: Add Python 3.12 to test matrix

tests/unit.tags
Two additional scenarios, verified by comparing the counts from the last run of the test suite against current.
=> Tests: Enable min-balance Cucumber tests.
