algosdk/constants.py, algosdk/transaction.py, test_unit.py
This PR proposes to add the AssetTransferTxn class to the python SDK, enabling: asset acceptance, asset transferral, asset clawback, asset mint, and asset burn. Like AssetConfig, it does not include helpers for distinguishing the uses of AssetTransferTxn, but does include documentation for how to use the class for these different functions.
Added a `golden` test to `test_unit.py`
=> Add AssetTransferTxn class

algosdk/constants.py, algosdk/encoding.py, algosdk/transaction.py, test_unit.py
This PR proposes to add a new `Transaction` subclass, `AssetFreezeTransaction`. It allows the freeze-manager of an asset to block an account from transferring assets, or for the freeze-manager to allow a frozen account to transfer assets.
New test added to `test_unit.py`, `test_serialize_assetfreeze`.
=> Support for asset freeze/un-freeze transactions

algosdk/encoding.py, algosdk/error.py, algosdk/template.py, algosdk/transaction.py, setup.py, test_unit.py
- add HTLC.get_transaction()
- new goldens
- includes changes from michelle/split
- new tests pass
=> template bug fixes

CHANGELOG.md, LICENSE, README.md, algosdk/algod.py, algosdk/auction.py, algosdk/encoding.py, algosdk/error.py, algosdk/kmd.py, algosdk/template.py, algosdk/transaction.py, docs/conf.py, example.py, setup.py, test_integration.py, test_unit.py
- add SuggestedParams object to handle fee, first valid round, last valid round, and genesis hash
- tests will fail since this is backwards incompatible
- locally updated tests are passing
=> implement suggested params

algosdk/v2client/indexer.py, test/steps/v2_steps.py
The `indexer` received an update to support rekey-related transactions. This PR proposes to likewise add support in the indexer client.
See https://github.com/algorand/algorand-sdk-testing/pull/81
=> Rekey-aware indexer client

algosdk/algod.py
Modified `send_raw_transaction` so that a `Content-Type: application/x-binary` header is set, only if the user didn't specify a Content-Type header.
This changes are backwards compatible, and address issue #68 .
@ejbaran @JasonWeathersby
=> Content-Type is now set when sending a transaction

algosdk/error.py, algosdk/future/transaction.py, algosdk/transaction.py, test_unit.py
Check it is a non-negative integer.
It is indeed otherwise possible to specify a floating amount
and only realize the error when sending the transaction.
=> Raises an exception if the amount field is incorrect

algosdk/constants.py, algosdk/error.py, algosdk/future/transaction.py, algosdk/transaction.py, test_unit.py
Check that:
* the note field is of type `bytes`.
* the note field is at most 1024-byte long.
Raises exception otherwise.
Without these checks, everything would appear to work but the transaction would be rejected by the node at the end (in the first case because the signature would be invalid).
=> Add checks that the note field is properly formed

algosdk/future/transaction.py
Previously, code like this:
transaction.ApplicationNoOpTxn(bidder, params, "10382")
would silently continue, but after signing and submitting, would
report:
algosdk.error.AlgodHTTPError: msgpack decode error [pos 93]: cannot decode unsigned integer: unrecognized descriptor byte: a8/string|bytes
This is a pretty obscure error to get for using a string id instead of
an int. We could type check and give an error when creating the
transaction, but Python APIs are usually more forgiving.  This change
calls int() on the index argument, so it will try to convert strings
if needed.
=> Convert APP and ASA indexes to ints.

algosdk/future/transaction.py, test_unit.py
Allow callers to specify args as strings, not just bytes, and
foreign_apps and assets as strings instead of just ints.  This makes
it more convenient to pull these things from environment variables.
=> Be forgiving about typing of app_args, foreign_a*

algosdk/future/transaction.py, algosdk/mnemonic.py, test_unit.py
Accept mnemonic words without regard to leading/trailing whitespace,
or the type of whitespace (we used to require exactly one space (no
newlines).  Words also work even if we only have the first for (or
more) letters, since they are guarenteed unique starting there, and
some key storage devices (crytosteel) explicitly tell you only to use
the first four letters.
This also speeds things up because we store the words in a
dict instead of a list.
=> Robust mnemonic

algosdk/future/transaction.py, algosdk/v2client/algod.py, test_unit.py
Reporting errors more clearly, we now detect and report several different typing errors at txn construction time, and fix #168 where an "empty" StateSchema is msgpacked wrong. (It shouldn't be packed at all.)
We also report attempts to send unsigned transactions.
=> Pack "empty" schema properly, detect the sending of unsigned transactions.

algosdk/constants.py, algosdk/error.py, algosdk/future/transaction.py, test_unit.py
A lease of 32 zeros should not be msgpacked, or we get signature
errors, as the Go code does not pack it.  Check and remove such leases
at Transaction construction time.
=> Do not msgpack empty leases.

algosdk/future/transaction.py, test_unit.py
Before, only online key registrations were supported.
Note: unit testing only test for `msgpack_decode` but not `future_msgpack_decode`.
However, I only made the change for "future" transactions.
I added some comments in `test_unit.py`.
=> Support for offline and non-participating key registration transactions

Makefile, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, test/steps/v2_steps.py
Add support for the new `include-all` query param on some indexer endpoints, and add support for relevant cucumber tests.
Like the JS SDK (algorand/js-algorand-sdk#296), the application endpoints also contained query params for `round`. I chose not to remove these arguments completely since that would cause a breaking change for anyone who calls the functions normally (i.e. without keyword args), so instead I've changed their descriptions to discourage use.
Closes #180.
=> Support new features for indexer 2.3.2

Makefile, algosdk/v2client/algod.py, test/steps/v2_steps.py
Add the missing `asset_info()` and `application_info()` methods to the v2 `AlgodClient` class.
Closes #188.
=> Add missing Algod endpoints

algosdk/v2client/indexer.py
Fix a typo and make it clearer that results with an amount equal to the value are excluded.
This is because usually "min" and "max" include the value
=> Fix typo in min/max balance indexer & make clearer

algosdk/util.py, algosdk/v2client/algod.py
Previously, under certain circumstances, if a developer passed their own `headers` to the `send_raw_transaction` method, the following error would occur:
```
TypeError: algosdk.v2client.algod.AlgodClient.algod_request() got multiple values for keyword argument 'headers'
```
This is because the headers defined in `send_raw_transaction` are passed along to `self.algod_request` with the headers that the Algorand SDK automatically passes. This creates duplicate header kwargs, resulting in the above `TypeError`. This PR attempts to solve this problem.
More context is provided in #169. CC: @jasonpaulos
=> Solve Issue #169: Merge Request headers in `algod.py`

algosdk/constants.py, algosdk/v2client/indexer.py
I was talking with a developer about writing code in python, and I too was familiar seeing constants across other SDKs as all uppercase. Thought it would be best to keep in line with general standards. Link to PEP 8 below:
https://www.python.org/dev/peps/pep-0008/#constants
=> modified: constants.py to match python.org PEP 8 style guidelines

algosdk/future/transaction.py, algosdk/v2client/algod.py
The current version of `py-algorand-sdk` doesn't work on Python < 3.7.
f-Strings was introduced in Python 3.7, so I changed it to a more general method (`str.format`) to be backward compatible.
=> Python < 3.7 bug fixed

algosdk/v2client/algod.py, algosdk/v2client/indexer.py, test/steps/v2_steps.py, test_integration.py
The following would always raise an exception in the `try` block and raise the second exception from the `except` without parsing the JSON `message` received in the HTTP response.
```python
try:
raise error.AlgodHTTPError(json.loads(e)["message"], code)
except:
raise error.AlgodHTTPError(e, code)
```
If the intent was to decode the JSON in the exception, this PR fixes the behaviour. Before: 
```
{"message":"TransactionPool.Remember: transaction CON6STFUWXIL3JHMHQOTSM5753NKOJKONGUVTD43DIG2P2ZRCMMA: asset 110 frozen in GSRKKDAQNOKAL4JJDJJLJUB3ZJFKTRI4NHXZ4QHYYPXSOE3EEWSWB43PRM"}
```
After:
```
TransactionPool.Remember: transaction CON6STFUWXIL3JHMHQOTSM5753NKOJKONGUVTD43DIG2P2ZRCMMA: asset 110 frozen in GSRKKDAQNOKAL4JJDJJLJUB3ZJFKTRI4NHXZ4QHYYPXSOE3EEWSWB43PRM
```
I have added a small …
=> Fix JSON decoding in AlgodHTTPError

algosdk/future/transaction.py
Fixes the following issues with the wait for confirmation function:
1. `pool-error` was being ignored
2. If the call to `pending_transaction_info ` raises an HTTP error, that error should be ignored and the function should continue retrying if `wait_rounds ` allows it.
3. Removed the special value 0 for `wait_rounds ` which allows indefinitely waiting. This is a dangerous feature, since your code might actually wait forever if it never sees the transaction fail. Instead a value of 1000 (the maximum txn life) is used to implement the same thing, and in reality is the longest you will ever have to wait. (Because v1.8.0 of this SDK was already released with this function, we can't get rid of the default value altogether without breaking the API).
4. Remove f-string use, which is not …
=> Fix wait for confirmation function

Dockerfile, README.md, requirements.txt
This PR makes a README change to add details to the development section and specify the `requirements.txt` to fetch the latest `behave` for tag support.
Thanks to @barnjamin for this suggestion 😃
=> Add requirement to fetch behave source code and update readme

CHANGELOG.md, Dockerfile, README.md, algosdk/abi/__init__.py, algosdk/abi/contract.py, algosdk/abi/interface.py, algosdk/abi/method.py, algosdk/abi/reference.py, algosdk/abi/transaction.py, algosdk/atomic_transaction_composer.py, algosdk/future/transaction.py, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, requirements.txt, setup.py, test/steps/v2_steps.py, test_unit.py
- Support Foreign objects as ABI arguments and address ARC-4 changes (#251)
- Add requirement to fetch behave source code and update readme (#262)
- Fix wait for confirmation function (#263)
- Add a default User-Agent header to the v2 algod client (#260)
=> FOR REVIEW ONLY - py-algorand-sdk v1.9.0b2

algosdk/future/transaction.py
While working with a new application with schema the state schema types need to be from the models package instead of the state schema from transactions since they use different encoding names
=> reformat local and global state to work with correct msgpack encoding

algosdk/future/transaction.py
When doing an appGlobalGetEx the values are extracted from the balance record of the app creator. If the app creator is not in the balance records passed in dryrun request the eval will report the application is not found
=> Add App creator to account balances

algosdk/__init__.py
I propose this change to help language servers with their work. Unless there is a good reason to keep v2 out of the \_\_init\_\_ file, I think the v2client should be added too.
=> Change __init__.py to include v2client import

.circleci/config.yml, .gitignore, algosdk/future/transaction.py, test_unit.py
Update circleci job to use docker instead of vms for unit tests. Also updated the unit tests to fail when they fail
=> Updates to pipeline

.circleci/config.yml, docs/.gitignore
This PR adds a CircleCI build step to generate docsets for [Kapeli's Dash](https://kapeli.com/dash) and [zeal](https://zealdocs.org). The result is uploaded as a CircleCI artifact.
I was doing these steps manually as I tend to access the docs quite often, so thought to automate it. If not useful/interesting we can just close this. :)
Looks like this:
=> Add CircleCI build step to generate docsets

docs/algosdk/abi/__init__.rst, docs/algosdk/abi/address_type.rst, docs/algosdk/abi/array_dynamic_type.rst, docs/algosdk/abi/array_static_type.rst, docs/algosdk/abi/base_type.rst, docs/algosdk/abi/bool_type.rst, docs/algosdk/abi/byte_type.rst, docs/algosdk/abi/contract.rst, docs/algosdk/abi/index.rst, docs/algosdk/abi/interface.rst, docs/algosdk/abi/method.rst, docs/algosdk/abi/reference.rst, docs/algosdk/abi/string_type.rst, docs/algosdk/abi/transaction.rst, docs/algosdk/abi/tuple_type.rst, docs/algosdk/abi/ufixed_type.rst, docs/algosdk/abi/uint_type.rst, docs/algosdk/atomic_transaction_composer.rst, docs/algosdk/index.rst, docs/requirements.txt
Tentatively add the ABI package and `atomic_transaction_composer` docs to Sphinx.
I have used an ugly command line to generate the `abi` files; might have missed something.
Also, first time using `sphinx` :)
=> Add ABI and ATC to Sphinx

test/steps/v2_steps.py
There was a [PR in the SDK testing repo](https://github.com/algorand/algorand-sdk-testing/pull/162) that changed the wording for one of the cucumber steps. This PR makes sure that the Python SDK steps conform to this wording change.
=> Fix cucumber tests for indexer asset lookup step

algosdk/testing/teal_blackbox.py
Optionally suggests a minor rename for consistency.  Since #298 applies the terminology _blackbox_, the PR suggests renaming from `BlackBoxResults` to `BlackboxResults`.
If the preference is to retain as is, then I welcome closing the PR.
=> Rename BlackBoxResults to BlackboxResults

algosdk/abi/tuple_type.py, algosdk/abi/ufixed_type.py, algosdk/abi/uint_type.py, algosdk/future/transaction.py, algosdk/util.py, requirements.txt, setup.py, test/steps/steps.py, test_unit.py
`pynacl`'s `VerifyKey()` can now return a [`TypeError` or `ValueError`](https://github.com/pyca/pynacl/blob/b3f6c320569d858ba61d4bdf2ac788564528c1c9/src/nacl/signing.py#L98) ([related PR](https://github.com/pyca/pynacl/pull/600/files)). Our SDK should reflect this change by catching those errors as well, or users may encounter an unexpected exception. 
Picked some major release versions and set that as boundaries. Hopefully users are using `venv` or `conda` as well...
* [pynacl](https://github.com/pyca/pynacl/tags)
* [msgpack](https://github.com/msgpack/msgpack-python/releases)
* [pycryptodomex](https://github.com/Legrandin/pycryptodome/releases)
Also added the `black` formatter updates so CI can run normally.
I didn't change the v1 `transaction` methods, but the problem is there as well …
=> Catch TypeError and ValueError in verify functions

README.md
Addresses README inconsistency between `pip` and `pip3` by normalizing on `pip3`.
=> Consistently reference `pip3` in README

algosdk/constants.py, algosdk/future/transaction.py, algosdk/testing/dryrun.py, test_unit.py
closes #316 
This should still raise a useful error in the case that close to is _also_ zero since that is likely user error.
=> adding condition for allowing rcv to be none if close to is set

.readthedocs.yaml
Attempts to fix docs since v1.13.0 by supplying missing dependencies.
v1.13.0 readthedocs build (https://readthedocs.org/api/v2/build/16801913.txt) shows errors (that don't fail the build) for a missing msgpack dependency:
```
WARNING: autodoc: failed to import module 'abi.address_type' from module 'algosdk'; the following exception was raised:
No module named 'msgpack'
```
These errors do _not_ appear in v1.12.0 build:  https://readthedocs.org/api/v2/build/16801915.txt.
=> Fix docs by providing root requirements.txt

algosdk/future/transaction.py
Currently `StateSchema.undictify()` is the only such method in the repo (out of 28 definitions) which does _not_ return an AlgoSDK object.
This PR addresses this discrepancy.
=> Make `StateSchema.undictify()` return an object

Makefile, run_integration.sh, test/steps/application_v2_steps.py, test/steps/other_v2_steps.py
>  I add a method call with the signing account, the current application, suggested params, on complete "noop", current transaction signer, current method arguments; any resulting exception has key "{none-or-exception-key}".
* https://github.com/algorand/algorand-sdk-testing/pull/190
* https://github.com/algorand/algorand-sdk-testing/pull/189
=> Implement new step asserting that AtomicTransactionComposer's attempt to add a method can fail with a particular error

tests/steps/account_v2_steps.py, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/steps/steps.py
Extends #360 to propose minimizing use of transactions to advance rounds.
=> Minimize use of transactions to advance rounds in #360

algosdk/abi/contract.py
This seems to choke the js-sdk which is expecting `string | undefined`
When there is a `None` in the dict, the json dumped includes `null`
```
>>> x = {'z':None}
>>> import json
>>> json.dumps(x)
'{"z": null}'
```
Other dictify methods have checks for this (Method/Args)
=> bug-fix: add check to desc so we dont output null if undefined

CHANGELOG.md, Makefile, algosdk/abi/contract.py, algosdk/logic.py, setup.py, tests/steps/account_v2_steps.py, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/steps/steps.py, tests/unit_tests/test_other.py
* bug-fix: add check to desc so we dont output null if undefined by @barnjamin in https://github.com/algorand/py-algorand-sdk/pull/368
* AVM:  Consolidate TEAL and AVM versions by @michaeldiamant in https://github.com/algorand/py-algorand-sdk/pull/361
* Testing: Modify cucumber steps to use dev mode network by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/360
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.16.0...v1.16.1
=> FOR REVIEW ONLY - py-algorand-sdk v1.16.1

.test-env, README.md, test-harness.sh
Following up from the companion [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224), we're going to pass through verbosity to the harness script via a new `-v` flag.
For further context: here is what [SDK Testing Bugfix PR](https://github.com/algorand/algorand-sdk-testing/pull/224) says:
> The sandbox is always defaulting to `release` and the generated `config.harness` isn't sticking because the verbose flag is provided in the wrong order. 
> 
> Additionally, after refactoring the SDK Sandboxization PR's to no longer overwrite `.env`, there is no way to pass through the verbosity, except by overwriting. The PR re-enables passing through by also reading `VERBOSE_HARNESS` as a flag (either `-v` or `--verbose`).
We can see that:
* previously the sandbox was …
=> Bug-fix: Pass verbosity through to testing harness

CHANGELOG.md, README.md, setup.py
we fixed readme on release branch
=> Mergeback: Release v1.17.0b1

algosdk/algod.py, algosdk/encoding.py, algosdk/future/transaction.py, algosdk/kmd.py, algosdk/template.py, algosdk/transaction.py
This PR adds deprecation warnings to v1 algod APIs and the old transaction format. In addition, there are warnings raised when the deprecated methods are called. 
The PR also adds a deprecation comment to `template` - previously, a similar comment was put in for `future.template`.
The `DeprecationWarning` that is added to this PR and the [langspec PR](https://github.com/algorand/py-algorand-sdk/pull/371/files) does trigger warnings on pytest (`pytest tests/unit_tests`). The corresponding tests should also be deleted when these features are removed from the SDK.
Related issue: https://github.com/algorand/algorand-sdk-testing/issues/218
=> Deprecation: Add deprecation warnings on v1 algod API and old transaction format

algosdk/box_reference.py, algosdk/v2client/algod.py, algosdk/v2client/indexer.py
Child PR to #348, which resolves my comments there
=> Minor improvements to boxes branch

.test-env, Makefile, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, setup.py, test-harness.sh, tests/steps/other_v2_steps.py, tests/unit.tags
Merges in develop and updates doc comments based on upstream changes one last time before merging the parent branch.
=> Merge in develop and update upstream doc comments

algosdk/error.py
This PR implements the `TransactionRejectedError` which was referenced within the logic of the `wait_for_confirmation` method despite being undefined.
This is a small PR to quickly fix the issue at hand, however future work is necessary to ensure that this class of errors is caught moving forward.
=> Bug-fix: Implement `TransactionRejectedError`

.test-env, algosdk/box_reference.py, algosdk/future/transaction.py
This PR changes how the `StateSchema` field, `accounts` field and `on_complete` fields are decoded. In addition, it makes a change to accept `BoxReferences` in addition to a list of app IDs and box names in `translate_box_reference()` (in the former case, no translation will be done). 
Related to https://github.com/algorand/algorand-sdk-testing/pull/248
=> Decoding: Fix roundtrip encode/decode tests for transactions

CHANGELOG.md, algosdk/box_reference.py, algosdk/error.py, algosdk/future/transaction.py, setup.py
* Bug-fix: Implement `TransactionRejectedError` by @jdtzmn in https://github.com/algorand/py-algorand-sdk/pull/396
* Decoding: Fix roundtrip encode/decode tests for transactions by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/398
**Full Changelog**: https://github.com/algorand/py-algorand-sdk/compare/v1.20.0...v1.20.1
=> FOR REVIEW ONLY: py-algorand-sdk v1.20.1

.test-env, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/steps/steps.py
Migrates algod v1 tests to use v2.
SDK Testing PR: https://github.com/algorand/algorand-sdk-testing/pull/249
In a future PR, it would be nice to refactor the `app_acl` to `aclv2` or even change it back to `acl` using the v2 client, as the name could be slightly confusing.
=> Tests: Migrate v1 algod dependencies to v2 in cucumber tests

README.md
Since we do not use Travis CI badge anymore, this PR deletes the badge from the README.
Optionally, we could also add the Circle CI badge to our README: https://circleci.com/docs/status-badges/#generating-a-status-badge
=> README: Delete Travis CI Badge 

README.md, examples/custom_header_example.py, examples/log_sig_example.py, examples/multisig_example.py, examples/notefield_example.py, examples/rekey_example.py, examples/tokens.py, examples/transaction_group_example.py
This PR changes the `examples` to use the `v2client` instead of v1 algod. 
As a sanity check, ran the examples on my local machine.
=> examples: Migrate v1 algod usage to v2 algod

CHANGELOG.md, algosdk/mnemonic.py, tests/steps/account_v2_steps.py, tests/steps/application_v2_steps.py, tests/unit_tests/test_transaction.py
Removes deprecated method `mnemonic.to_public_key` as part of v2.0.0 release.  https://github.com/algorand/py-algorand-sdk/pull/207 deprecated the method > 1 year ago.
=> Remove deprecated mnemonic.to_public_key

CHANGELOG.md
Extends https://github.com/algorand/py-algorand-sdk/pull/415 with CHANGELOG entries for already merged breaking changes.  Upon merging the PR, the CHANGELOG _should_ be complete.
=> Add remaining v2.0.0 breaking change CHANGELOG entries

algosdk/transaction.py
Adds LogicSig usage disclaimer suggesting LogicSigAccount usage as a more general purpose signing mechanism.
=> LogicSig: Add LogicSig usage disclaimer

MANIFEST.in, setup.py
This PR removes some extra references to`langspec.json`, which has been removed as of v2.x. 
#384
=> v2: Delete more references to `langspec`

setup.py
This PR fixes `setup.py` so only `algosdk` and its subdirectories are installed. 
Locally tested:
* Delete `*.egg-info` and `build` directories
* Run `pip install .`
* Check that only `algosdk` is included in the install in `site-packages`. `tests` and `examples` are no longer shipped with the installation, which may address #374 as well.
Closes #408
=> Infrastructure: Only package `algosdk` in `setup.py`

.circleci/config.yml, setup.py
This PR adds a check to see if `setup.py` is well-formed. It also removes the `v` prefix from the version, as it does not seem necessary [(related change)](https://github.com/algorand/py-algorand-sdk/commit/66660112154f85a17a5ccfd9ec36d28a6236dbbb#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R12) and generates a user warning: 
```
dist.py:487: UserWarning: Normalizing 'v1.20.2' to '1.20.2'
warnings.warn(tmpl.format(**locals()))
```
Closes https://github.com/algorand/py-algorand-sdk/issues/409
=> Infrastructure: Add setup.py check to circle ci

algosdk/atomic_transaction_composer.py, algosdk/dryrun_results.py, mypy.ini
=> bugfix: fix msig sks type + a couple other mypy complaints

algosdk/error.py
Hi, Ori from the Foundation here.
I'm getting the following error when calling `AlgodClient.block_info(None)`
```
__init__() missing 1 required positional argument: 'contract_type'
```
Looked in the code and realized that both `OverspecifiedRoundError` and `UnderspecifiedRoundError` expect the unused positional argument `contract_type`. This PR fixes that.
=> fix: remove unused positional argument "contract_type" from OverspecifiedRoundError and UnderspecifiedRoundError

algosdk/v2client/algod.py, tests/integration.tags, tests/steps/other_v2_steps.py
This PR adds support for `/v2/teal/disassemble` and corresponding tests from https://github.com/algorand/algorand-sdk-testing/pull/251.
Since py-algorand-sdk endpoint support is not auto-generated, the PR adds support following conventions from the compile endpoint.
=> Algod: Add disassembly endpoint and implement cucumber test

.test-env
forgot to revert the test-env in the Simulate SDK merge
=> Fix: Revert .test-env in develop

.circleci/config.yml, .test-env, CHANGELOG.md, Makefile, README.md, algosdk/__init__.py, algosdk/__init__.pyi, algosdk/abi/__init__.py, algosdk/abi/interface.py, algosdk/abi/method.py, algosdk/atomic_transaction_composer.py, algosdk/dryrun_results.py, algosdk/error.py, algosdk/source_map.py, algosdk/testing/dryrun.py, algosdk/transaction.py, algosdk/v2client/__init__.py, algosdk/v2client/algod.py, algosdk/v2client/indexer.py, algosdk/v2client/models/__init__.py, mypy.ini, requirements.txt, scripts/generate_init.py, setup.py, tests/integration.tags, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py, tests/unit_tests/test_logicsig.py
Adding the simulate, disassembly endpoint support.
* bugfix: fix msig sks type + a couple other mypy complaints by @barnjamin in https://github.com/algorand/py-algorand-sdk/pull/434
* fix: remove unused positional argument "contract_type" from OverspecifiedRoundError and UnderspecifiedRoundError by @ori-shem-tov in https://github.com/algorand/py-algorand-sdk/pull/438
* Fix: Revert .test-env in develop by @bbroder-algo in https://github.com/algorand/py-algorand-sdk/pull/445
* New Feature: Adding methods to use the simulate endpoint by @barnjamin in https://github.com/algorand/py-algorand-sdk/pull/420
* Infrastructure: Add setup.py check to circle ci by @algochoi in https://github.com/algorand/py-algorand-sdk/pull/427
* Enhancement: Type Friendly Exports by @tzaffi in …
=> FOR REVIEW ONLY: py-algorand-sdk v2.1.0

algosdk/transaction.py, algosdk/v2client/algod.py
Adds type parameter of GenericSignedTransaction to a couple places that had explicitly listed SignedTransaction types
=> Fix: improve SignedTransaction type signature for dryrun and send_transaction

.test-env, algosdk/atomic_transaction_composer.py, algosdk/v2client/algod.py, algosdk/v2client/models/__init__.py, algosdk/v2client/models/simulate_request.py, tests/steps/other_v2_steps.py
Support the changes to simulate from https://github.com/algorand/go-algorand/pull/5292
=> API: Support updated simulate endpoint

.test-env, algosdk/atomic_transaction_composer.py, algosdk/constants.py, algosdk/v2client/algod.py, tests/environment.py, tests/integration.tags, tests/steps/other_v2_steps.py, tests/unit.tags
This PR implements the devmode timestamp offset, sync, and ready endpoints in the Python SDK.
Tested locally and added some cucumber tests.
=> algod: Add endpoints for devmode timestamps, sync, and ready

algosdk/v2client/indexer.py, docs/algosdk/index.rst
This is a non-functional change
* #471
* #475
=> bugfix: incorrect indexer docs

algosdk/transaction.py
Define the `GenericSignedTransaction` type alias after the Transaction types have been defined and before its first usage.
=> tweak: reorder GenericSignedTransaction type alias

docs/algosdk/box_reference.rst, docs/algosdk/index.rst, docs/conf.py
This addresses a small portion of #419 .
Verified locally that I was able to get the page:
=> Enhancement: Adding `box_reference.py` to Read The Docs

.test-env, algosdk/v2client/algod.py, tests/steps/other_v2_steps.py, tests/unit.tags
Implement group state delta endpoints and tests in https://github.com/algorand/algorand-sdk-testing/pull/281/files.
=> algod: State delta endpoints

.test-env
To improve visibility of C.I. build failures, utilize new logging capabilities in the sandbox (https://github.com/algorand/sandbox/pull/181) and set `VERBOSE_HARNESS=1`.
In particular we can now see:
* traces of the `docker compose up` command
* dumped `docker-compose logs` for:
* indexer-db
* algod
* indexer
For more information about the effects of this PR on testing in C.I. see the sibling go-sdk pr: https://github.com/algorand/go-algorand-sdk/pull/540
=> Enhancement: verbose harness

.circleci/config.yml, .github/workflows/create-release-pr.yml
Move slack messaging to include more details and as part of github actions instead of CircleCI.
Tested in our experimental channel from a testing repo.
=> CICD: Move slack messaging to github actions

.github/workflows/create-release-pr.yml
Remove teams as reviewers. There seems to be unresolved issues with permissions for github actions to properly assign teams as reviewers: https://github.com/cli/cli/issues/6395
cc:
@algorand/devops
=> CICD: Remove Reviewers

.circleci/config.yml, .git-blame-ignore-revs
Adds a `.git-blame-ignore-revs` to exclude formatting commits in the git history. This makes it easier to trace the git blame from source code. To enable locally, you may have to edit your Git settings: `git config blame.ignoreRevsFile .git-blame-ignore-revs`.
Visually confirmed in the Github blame viewer on this branch - there are some occasional lines that slip through, but I think it's a problem with the UI.
=> other: Ignore formatting commits in git blame

.circleci/config.yml, .github/workflows/create-release-pr.yml, scripts/bump_version.py
After the previous release, noticed a few things to improve:
1. "Enhancement" sub-header should be "Enhancements" in the release notes
2. The `${RELEASE_TAG}` is redundant when you add a title to the release. Removing release tag here aligns with our previous releases.
3. Authors in the Release notes should be prefaced with a `@`
4. Add `Team Hyper Flow` to the PRs so we can easily track and make sure PRs get merged and not forgotten
5. Swap out the changelog-builder with github api
Tested workflow in a separate repo.
=> CICD: Fix typos and add team label to release PR workflow

.test-env, algosdk/v2client/indexer.py
This PR fixes [#296](https://github.com/algorand/py-algorand-sdk/issues/296)
=> bug-fix: include currency-greater-than param for 0 value

docs/algosdk/dryrun_results.rst, docs/algosdk/index.rst, docs/algosdk/source_map.rst
Add submodules that previously were missing from our docs.
To test, I generated the docs locally and confirmed this fixes the issue.
=> Docs: Add missing pages for source map and dryrun results

examples/participation.py
This fixes a typographical error when intending to print offline participation.
=> Fix typographic error when printing offline participation transaction

algosdk/transaction.py
Rather than use a hard coded constant for min_fee, use the one that is returned in SuggestedParams if available.
Since some people may create a SuggestedParams by hand rather than get one from server (because our APIs require one even though the caller may feel they "know better"), continue to use the constant if the sp.min_fee is None.
First noted by @plasmatech8 in #299
=> txns: Uses sp.min_fee if available

algosdk/atomic_transaction_composer.py, algosdk/v2client/models/simulate_request.py, tests/integration.tags, tests/steps/application_v2_steps.py, tests/steps/other_v2_steps.py
This SDK is behind on support for simulate options. This PR adds all simulate request options that are currently available in algod.
Similar to this JS PR: https://github.com/algorand/js-algorand-sdk/pull/818
Closes #519, closes #536
=> Simulate: Support newer simulate options

algosdk/error.py, algosdk/v2client/algod.py, examples/inspect-error.py, examples/utils.py
Previously, if we caught a urllib.error.HTTPError, we would try to parse the json response. If we succeeded we would return _only_ the `message` field of that response. If we failed, we're return the text of the response.  By "return" here, I actually mean "pack up into an Exception object and throw it".
Now, if succeed in parsing the response as json, we extend that exception object so that it also contains the JSON that we got. That way, client code can find extra goodies in the json["data"] field.
Also added a utility to the examples so they can be easily run against a locally running `algod`.
=> algod: Even in the face of urllib.error.HTTPError, return the json

algosdk/kmd.py
#527 introduced a default timeout of 30s for KMD, algod, and indexer requests.
Algod and indexer use kwargs to pass extra arguments to their underlying `algod_request` & `indexer_request` functions, including `timeout`.
Unfortunately KMD had no such functionality, so it's impossible to change the default 30s timeout. This PR adds kwargs to all KMD functions to forward parameters like `timeout` to `kmd_request`.
=> Fix: Pass args to underlying `kmd_request` function, including timeout

algosdk/v2client/algod.py, tests/steps/other_v2_steps.py
This PR adds support for a new header-only=true parameter to the '/v2/block/{round}' endpoint. Includes support for cross-SDK test cases.
=> API: Support for header-only flag on /v2/block algod endpoint.

.circleci/config.yml, tests/steps/application_v2_steps.py
The pagination support on the Algod boxes endpoint depends solely on what box information has been persisted within algod. Previously, integration tests could assume once a transaction to add a box was approved, it was queryable. This PR introduces check and wait semantics to give ample time for the boxes to be made available via API.
=> Build: Update Box API Pagination-dependent integration tests

.github/workflows/ci-pr.yml, Dockerfile, Makefile
This PR implements unit and integration tests in GitHub actions.
I stripped the docker container build in integration tests (though left sandbox instantiation).
Verify these tests pass.
=> CICD: implement tests in GitHub Actions
